// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuwsvkujqvochetcgnyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1d3N2a3VqcXZvY2hldGNnbnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDgyNTMsImV4cCI6MjA1OTc4NDI1M30.Pok06RB1iuk5-pbUpl0hT8bxZQoS9j28wZp04bWzsI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);